import pandas as pd


def autogenerate_sheet(sheet1, sheet2):
    # Getting artists from sheet1 and track
    artists = sheet1['Artist']
    track = sheet1['Track']

    # Creating dictionary with artist and its track
    artists_track_dict = {}
    for i in range(len(artists)):
        if track[i] in artists_track_dict:
            if not isinstance(artists_track_dict[track[i]], list):
                # If type is not list then make it list
                artists_track_dict[track[i]] = [artists_track_dict[track[i]]]
            artists_track_dict[track[i]].append(artists[i])
        else:
            artists_track_dict[track[i]] = artists[i]

    # Converting artists data to list and adding a empty value to start so that it will be acted as columns
    artists = list(artists)
    artists.insert(0, ' ')  # First column empty

    # Making list of zeros
    zero_list = []
    for i in range(len(artists) - 1):
        zero_list.append(0)

    dict = {}

    # iterating through the elements of list and adding items in dictionary
    # Also creating dictionary for index of each artist
    index = 0
    index_dict = {}
    for artist in artists:
        index_dict[artist] = index
        index += 1

        if artist == ' ':
            dict[artist] = artists[1:]
        else:
            dict[artist] = zero_list

    # Converting dictionary to data frame
    insert_df = pd.DataFrame(dict)

    # Now reading sheet2 to get all values of 2 artists in a dict
    Artist = list(sheet2['Artist'])
    Artist_2 = list(sheet2['Artist_2'])
    Records_Sold = list(sheet2['Records_Sold'])
    Album = list(sheet2['Album'])

    for i in range(len(Artist)):
        # Adding value to the cell where artist_1 as row number and artist_2 as column
        if Artist[i] in artists and Artist_2[i] in artists:
            insert_df.loc[index_dict[Artist[i]] - 1, Artist_2[i]] = Records_Sold[i]

    # Getting Album with artists and storing in array
    albums_with_artists = {}
    for i in range(len(Artist)):
        if Artist[i] != Artist_2[i]:
            albums_with_artists[Artist[i], Artist_2[i]] = Album[i]
            # albums_with_artists[Album[i]] = [Artist[i], Artist_2[i]]

    # print(albums_with_artists)
    # print(artists_track_dict)
    # Updating data frame for -ve values
    for key, value in albums_with_artists.items():
        artists_values = artists_track_dict[value]
        for artist_value in artists_values:  # Iterating through all artists of an album
            temp_artist = artist_value
            if temp_artist in artists:  # Check if artist is in artist list or ont
                insert_df.loc[index_dict[temp_artist] - 1, key[0]] = -1
                insert_df.loc[index_dict[temp_artist] - 1, key[1]] = -1
    return insert_df


# Opening Excel file and reading all sheets
df = pd.read_excel('test2.xlsx', sheet_name=None)  # read all sheets

# Now getting data of all sheets separately
sheet1 = df['Sheet1']
sheet2 = df['Sheet2']
# Calling the function to get back auto-generated sheet3
sheet3 = autogenerate_sheet(sheet1, sheet2)

# Generating new excel sheet where data will be Added
writer = pd.ExcelWriter('Sheet3_AutoGenerated.xlsx', engine='xlsxwriter')
writer.save()

# Adding sheet3 to excel file
sheet3.to_excel('Sheet3_AutoGenerated.xlsx')
