import pandas as pd

# Opening Excel file and reading all sheets
df = pd.read_excel('test2.xlsx', sheet_name=None)  # read all sheets

# Now getting data of all sheets separately
sheet1 = df['Sheet1']
sheet2 = df['Sheet2']

# Getting artists from sheet1 and track
artists = sheet1['Artist']
track = sheet1['Track']

# Creating dictionary with artist and its track
artists_track_dict = {}
for i in range(len(artists)):
    if track[i] in artists_track_dict:
        artists_track_dict[track[i]] = [artists_track_dict[track[i]], artists[i]]
    else:
        artists_track_dict[track[i]] = artists[i]


# Converting artists data to list and adding a empty value to start so that it will be acted as columns
artists = list(artists)
artists.insert(0, ' ')  # First column empty

# Making list of zeros
zero_list = []
for i in range(len(artists) - 1):
    zero_list.append(0)

dict = {}

# iterating through the elements of list and adding items in dictionary
# Also creating dictionary for index of each artist
index = 0
index_dict = {}
for artist in artists:
    index_dict[artist] = index
    index += 1

    if artist == ' ':
        dict[artist] = artists[1:]
    else:
      dict[artist] = zero_list

# Converting dictionary to data frame
insert_df = pd.DataFrame(dict)

# Now reading sheet2 to get all values of 2 artists in a dict
Artist = list(sheet2['Artist'])
Artist_2 = list(sheet2['Artist_2'])
Records_Sold = list(sheet2['Records_Sold'])
Album = list(sheet2['Album'])

Sheet2_Dict = {}
for i in range(len(Artist)):
    Sheet2_Dict[Records_Sold[i]] = [Artist[i], Artist_2[i]]

# Updating data frame
for key, value in Sheet2_Dict.items():
    insert_df.loc[index_dict[value[0]]-1, value[1]] = key

# Getting Album with artists and storing in array
albums_with_artists = {}
for i in range(len(Artist)):
    if Artist[i] != Artist_2[i]:
        albums_with_artists[Album[i]] = [Artist[i], Artist_2[i]]

# Updating data frame
print (insert_df )
for key, value in albums_with_artists.items():
    artists_values = artists_track_dict[key]
    artist_1 = artists_values[0]
    artist_2 = artists_values[1]
    # Updating values of first artist
    insert_df.loc[index_dict[artist_1]-1, value[0]] = -1
    insert_df.loc[index_dict[artist_1]-1, value[1]] = -1
    # Now second
    insert_df.loc[index_dict[artist_2]-1, value[0]] = -1
    insert_df.loc[index_dict[artist_2]-1, value[1]] = -1

# Adding created dictionary in new generated sheet
# Generating new excel sheet where data will be auto-generated
writer = pd.ExcelWriter('Sheet3_AutoGenerated.xlsx', engine='xlsxwriter')
writer.save()

# Adding dataframe to excel file
insert_df.to_excel('Sheet3_AutoGenerated.xlsx')
